version: '3'

services:
  jupyops:
    build: 
      context: ./Dockerfiles
      dockerfile: Dockerfile.jupyops
    image: jupyops:latest
    container_name: jupyops
    hostname: jupyops
    ports: # HOST:CONTAINER
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    volumes:
      - repo:/GradePredictionData
      - data:${APP_ROOT}/data
      - notebooks:/home/jovyan/work
      - log:${APP_ROOT}/log
      - src:${APP_ROOT}/src
      - scripts:${APP_ROOT}/scripts
    command: ["start.sh", "jupyter", "lab", "--LabApp.token=''"]
    stdin_open: true
    tty: true

#
# Volume definition
# 
volumes:
  repo:
    driver: local
    driver_opts:
      type: none
      device: ${VOL_DIR}/
      o: bind
  log:
    driver: local
    driver_opts:
      type: none
      device: ${VOL_DIR}/log
      o: bind
  notebooks:
    driver: local
    driver_opts:
      type: none
      device: ${VOL_DIR}/notebooks
      o: bind
  src:
    driver: local
    driver_opts:
      type: none
      device: ${VOL_DIR}/src
      o: bind
  scripts:
    driver: local
    driver_opts:
      type: none
      device: ${VOL_DIR}/scripts
      o: bind
  docs:
    driver: local
    driver_opts:
      type: none
      device: ${VOL_DIR}/docs
      o: bind
  data:
    driver: local
    driver_opts:
      type: none
      device: ${VOL_DIR}/data
      o: bind
